apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-08-05T10:02:28Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx-deployment
  name: nginx-deployment-service
  namespace: default
  resourceVersion: "38656"
  uid: 29df4faa-c4e2-4479-84c8-ada55caf612d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.234.11
  clusterIPs:
  - 34.118.234.11
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32218
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.16.78.255
      ipMode: VIP
