name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускати CI/CD на push у main гілку

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker
          gcloud auth configure-docker us-central1-docker.pkg.dev
    


    
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/custom-nginx-deployment-image:latest .
          
      - name: Push Docker image to GCR
        run: |
          docker images
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/custom-nginx-deployment-image:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Запустити після завершення build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Kubernetes
        uses: google-github-actions/setup-gcloud@v1
        

      - name: Configure kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f nginx-deployment.yaml
      - name: Update image in Kubernetes deployment
        run: |
          kubectl set image deployment/nginx-deployment nginx=gcr.io/${{ secrets.GCP_PROJECT_ID }}/custom-nginx-deployment-image:latest
