name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускати CI/CD на push у main гілку

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Determine version tag
        id: get_version
        run: |
          VERSION_TAG=${{ github.run_number }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            VERSION_TAG="latest"
          elif [ "${{ github.ref }}" == refs/tags/* ]; then
            VERSION_TAG="${{ github.ref_name }}"
          else
            VERSION_TAG="${{ github.run_number }}"
          fi
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
    


    
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/custom-nginx-deployment-image:${{ env.VERSION_TAG }} .
          
      - name: Push Docker image to GCR
        run: |
          docker images
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/custom-nginx-deployment-image:${{ env.VERSION_TAG }}

